# syntax=docker/dockerfile:1

FROM python:3.9-slim

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London
ENV POETRY_VIRTUALENVS_CREATE=true \
    POETRY_VERSION=1.5.1 \
    YOUR_ENV=development
# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# Configure Poetry
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/opt/.cache
ENV PATH "/root/.local/bin:$PATH"

# Install poetry separated from system interpreter
RUN python3 -m venv $POETRY_VENV \
    && $POETRY_VENV/bin/pip install -U pip setuptools \
    && $POETRY_VENV/bin/pip install poetry==${POETRY_VERSION}

WORKDIR /app

#COPY requirements.txt requirements.txt

ADD ./requirements.txt /app/requirements.txt
RUN $POETRY_VENV/bin/pip install -r requirements.txt

ADD . /app

RUN apt-get update && apt-get install libgl1 libglib2.0-0 git -y

#RUN $POETRY_VENV/bin/poetry install $(test "$YOUR_ENV" == production && echo "--no-dev") --no-interaction --no-ansi

CMD ["/opt/poetry-venv/bin/python", "il_5safe/server.py" ]
